---

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install needed packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - python3
     - python3-pip
     - nginx


...
