---

- name: Update packages
  apt:
    update_cache: yes
    upgrade: yes

- name: Install needed packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
     - aptitude
     - python3
     - python3-pip
     - nginx
     - supervisor
     - lsof
     - git

- name: Disable nginx on boot
  systemd:
    name: nginx
    state: stopped
    enabled: no

- name: Enable supervisor on boot
  systemd:
    name: supervisor
    state: restarted
    enabled: yes

- name: Create pip to pip3 symlink
  file:
    src: /usr/bin/pip3
    dest: /usr/bin/pip
    state: link


...
